### ISSUE TITLE
Logo for the website

### ISSUE THREAD

**Issue by jibin2706** [jibin2706/blog.jibin.tech#1]
Currently it uses just text as logo 'Jibin Thomas'. If anyone can create a logo using the name or initial it would be cool.

**Comment by Guzzler** [comment]
Hey i have something i made up with simple brush stroke art work with the initials. Should i just create a PR with it or would it be subject to review here first? It is a simple logo that is a play on the Pi symbol and the initials JT

**Comment by Guzzler** [comment]
![JT Logo Red Spray](https://user-images.githubusercontent.com/12707741/66030217-8b475c00-e51e-11e9-8c03-ee54c6540081.png)

**Comment by kshitij86** [comment]
Could you mention the specifications for the logo.

**Comment by jibin2706** [comment]
Modern looking or calligraphy logo with Initials `JT` or full name `Jibin Thomas` which should look good will the site.

**Comment by jibin2706** [comment]
You can show the preview of the logo here before making the PR.
